version: '3.8'
services:
    web:
        image: chessgirl/php-nginx-test
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: chessgirl/mysql-test
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
